[project]
readme = "README.md"
python = "3.9"

[tool.isort]
profile = "black"
force_single_line = true
line_length = 79
py_version = 39
extend_skip = [".md"]

[tool.black]
line-length = 79
target-version = ['py39']
